
title: Knowledge Base
description: An archive of my personal knowledge base (created and saved as a blog).
author:
  name: Cristian Sulea
  email: your-email@domain.com

#theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

###

collections_dir: content

collections:
  blog:
    output: true
    sort_by: date

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "index"
      author: "Cristian Sulea"
      permalink: /:collection/:name
  - scope:
      path: "_blog/xyz"
      type: "blog"
    values:
      layout: "index"
      author: "Cri Sul"
  - scope:
      path: ""
    values:
      layout: "index"